### ISSUE TITLE
docker feedback

### ISSUE THREAD

**Issue by ldemailly** [EchoVault/EchoVault#87]
(saw your post on discord, grats/nice)

Some feedback:

in Dockerfile.prod you have FROM homebrew/brew:latest

Have you swapped accidentally .prod and .dev?

And for whichever ends up the real prod:

Take a Quick Look at https://laurentsv.com/blog/2024/06/25/stop-the-go-and-docker-madness.html

ie you can reduce your docker final image a lot (FROM scratch ftw)

ps: while I'm at it... why cmd/main.go ... move it up?

**Comment by kelvinmwinuka** [comment]
Hi @ldemailly thanks for the docker feedback. I'm reading through the article and I like that approach. Since we aren't building prod docker images yet, there's still time to make adjustments to this.

With regard to cmd/main.go, I structured it like that in the early stages of the project when the folder structure was a lot more chaotic. There's definitely no downside moving it up.
